name: Terraform Grafana

on:
  push:
    branches: [ main ]
    paths:
      - "**.tf"
      - "dashboards/**"
      - "teams/**"
      - "modules/**"
  workflow_dispatch: {}

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_grafana_url: ${{ secrets.GRAFANA_URL }}
      TF_VAR_grafana_api_token: ${{ secrets.GRAFANA_API_TOKEN }}
      TF_VAR_ds_prometheus: ${{ secrets.DS_PROMETHEUS }}
      TF_VAR_ds_loki: ${{ secrets.DS_LOKI }}
      TF_VAR_ds_tempo: ${{ secrets.DS_TEMPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug Terraform Token Visibility
        run: |
          echo "TF_API_TOKEN is set: ${TF_API_TOKEN:+yes}"
          echo "TF_TOKEN_app_terraform_io is set: ${TF_TOKEN_app_terraform_io:+yes}"
        shell: bash

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
